app:
  name: "backend-modAppRest"
  version: "0.0.1"
database:
  uri: postgres://green:0010@rest-postgres-1:5433/regina
jwt:
  sign_key: "regina"
  access_expiry: 24h
  refresh_expiry: 72h
http:
  port: 8080
  read_timeout: 1m
  write_timeout: 1m
  shutdown_timeout: 5s
